import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Dell Active Pen',
      slug: 'dell-active-pen',
      category: 'Tech Equipment',
      image: '/images/p1.jpg',
      price: 64,
      countInStock: 1,
      condition: 'Brand New',
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pen',
    },
    {
      //_id: '2',
      name: 'Noise Cancelling Headphones',
      slug: 'noise-cancelling-headphones',
      category: 'Tech Equipment',
      image: '/images/p2.jpg',
      price: 199,
      countInStock: 0,
      condition: 'Brand New',
      brand: 'Urbanista',
      rating: 4,
      numReviews: 10,
      description: 'high quality headphones',
    },
    {
      //_id: '3',
      name: 'Logo Subject Notebook',
      slug: 'logo-subject-notebook',
      category: 'Books',
      image: '/images/p3.jpg',
      price: 6,
      countInStock: 1,
      condition: 'Brand New',
      brand: 'CSUF',
      rating: 4.5,
      numReviews: 8,
      description: 'high quality notebook',
    },
    {
      //_id: '4',
      name: 'J Hook Lanyard',
      slug: 'j-hook-lanyard',
      category: 'Supplies',
      image: '/images/p4.jpg',
      price: 11,
      countInStock: 1,
      condition: 'Brand New',
      brand: 'CSUF',
      rating: 5.0,
      numReviews: 9,
      description: 'high quality lanyard',
    },
  ],
};
export default data;
