const data = {
  products: [
    {
      name: 'Dell Active Pen',
      slug: 'dell-active-pen',
      category: 'Tech Equipment',
      image: '/images/p1.jpg',
      price: 64,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pen',
    },
    {
      name: 'Noise Cancelling Headphones',
      slug: 'noise-cancelling-headphones',
      category: 'Tech Equipment',
      image: '/images/p2.jpg',
      price: 199,
      brand: 'Urbanista',
      rating: 4,
      numReviews: 14,
      description: 'high quality headphones',
    },
    {
      name: 'Logo Subject Notebook',
      slug: 'logo-subject-notebook',
      category: 'Books',
      image: '/images/p3.jpg',
      price: 6,
      brand: 'CSUF',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality notebook',
    },
    {
      name: 'J Hook Lanyard',
      slug: 'j-hook-lanyard',
      category: 'Supplies',
      image: '/images/p4.jpg',
      price: 11,
      brand: 'CSUF',
      rating: 3.5,
      numReviews: 14,
      description: 'high quality lanyard',
    },
  ],
};
export default data;
